name: Release to Production
on:
  workflow_dispatch: {}
jobs:
  semantic-release:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.semantic.outputs.release-version }}
    steps:
      - uses: actions/checkout@v3
      - uses: cycjimmy/semantic-release-action@v3
        id: semantic
        with:
          semantic_version: 19.0.5
          extra_plugins: |
            conventional-changelog-conventionalcommits@6.1.0
            @semantic-release/commit-analyzer@9.0.2
            @semantic-release/release-notes-generator@10.0.3
            @semantic-release/npm@9.0.2
            @semantic-release/github@8.0.7
            @semantic-release/git@10.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: fail if no version
        if: steps.semantic.outputs.new-release-published == 'false'
        run: exit 1
  deploy:
    needs: semantic-release
    uses: ./.github/workflows/production-deploy.yaml
    secrets: inherit
    with:
      version: ${{ needs.semantic-release.outputs.version }}

